#!/usr/bin/env php
<?php

// if you don't want to setup permissions the proper way, just uncomment the following PHP line
// read http://symfony.com/doc/current/book/installation.html#configuration-and-setup for more information
//umask(0000);

set_time_limit(0);

require_once __DIR__.'/bootstrap.php.cache';
require_once __DIR__.'/AppKernel.php';

//use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Debug\Debug;

use Bundle\ProjectBundle\Command\GreetCommand;
use Bundle\ProjectBundle\Command\InsertCommand;
use Bundle\ProjectBundle\Command\InsertPlacesCommand;

use Symfony\Component\Console\Application;

// demo command - Greet
//$application = new Application();
//$application->add(new GreetCommand);
//$application->run();

// insert ip command
//$app = new Application();
//$app->add(new InsertCommand);
//$app->run();

// insert places command
$app1 = new Application();
$app1->add(new InsertPlacesCommand);
$app1->run();

$input = new ArgvInput();
$env = $input->getParameterOption(array('--env', '-e'), getenv('SYMFONY_ENV') ?: 'dev');
$debug = getenv('SYMFONY_DEBUG') !== '0' && !$input->hasParameterOption(array('--no-debug', '')) && $env !== 'prod';

if ($debug) {
    Debug::enable();
}

$kernel = new AppKernel($env, $debug);
$application = new Application($kernel);
$application->run($input);
